#!/bin/bash

bow_app="Freq"
echo $bow_app

./run_test.sh 1234 Apollo.ApolloConfigDemo.66.ApolloConfigDemo.main.truepositive-$bow_app.arff
./run_test.sh 1234 Apollo.ConsumerAuthenticationFilterTest.70.ConsumerAuthenticationFilterTest.testAuthFailed.falsepositive-$bow_app.arff
./run_test.sh 1234 Apollo.CtripLogoutHandler.28.CtripLogoutHandler.logout.truepositive-$bow_app.arff
./run_test.sh 1234 Apollo.CtripLogoutHandler.39.CtripLogoutHandler.logout.truepositive-$bow_app.arff
./run_test.sh 1234 Apollo.LocalFileConfigRepository.74.LocalFileConfigRepository.\<init\>.falsepositive-$bow_app.arff
./run_test.sh 1234 Apollo.LocalFileConfigRepository.80.LocalFileConfigRepository.\<init\>.falsepositive-$bow_app.arff
./run_test.sh 1234 Apollo.LocalFileConfigRepository.271.LocalFileConfigRepository.\<init\>.falsepositive-$bow_app.arff
./run_test.sh 1234 Apollo.NamespaceService.131.NamespaceService.findNamespaceBOs.falsepositive-$bow_app.arff
./run_test.sh 1234 Apollo.ResourceUtils.52.MetaDomainConsts.\<init\>.falsepositive-$bow_app.arff
./run_test.sh 1234 Apollo.SimpleApolloConfigDemo.45.SimpleApolloConfigDemo.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.AbstractUserArgumentProcessor.338.CeCPMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.AbstractUserArgumentProcessor.342.CeMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.AFPChainXMLParser.235.JFatCatClient.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.AllChemCompProvider.101.AllChemCompProvider.ensureFileExists.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.AllChemCompProvider.128.AllChemCompProvider.downloadFile.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.AllChemCompProvider.153.AllChemCompProvider.getLocalFileName.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.Astral.224.Astral.getRepresentatives.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.Astral.229.Astral.getRepresentatives.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.BiologicalAssemblyTransformation.239.RemoteBioUnitDataProvider.getBioUnitTransformationList.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.CallableStructureAlignment.178.CallableStructureAlignment.call.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.ChemCompGroupFactory.116.ChemCompTest.testMEA.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.DownloadChemCompProvider.112.ChemCompDistribution.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.DownloadChemCompProvider.217.ChemCompDistribution.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.DownloadChemCompProvider.329.ChemCompDistribution.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.DownloadChemCompProvider.329.ChemCompGroupFactory.getChemComp.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.DownloadChemCompProvider.338.PDBFileReader.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.EcodInstallation\$EcodParser.517.EcodInstallation.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.EcodInstallation\$EcodParser.577.EcodInstallation.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.EcodInstallation\$EcodParser.586.EcodInstallation.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.EcodInstallation\$EcodParser.589.EcodInstallation.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.FastaAFPChainConverter.402.FastaAFPChainConverter.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.GuiWrapper.216.FatCat.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.HasResultXMLConverter.78.JFatCatClient.hasPrecalculatedResult.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.JFatCatClient.121.JFatCatClient.hasPrecalculatedResult.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.JFatCatClient.255.JFatCatClient.sendMultiAFPChainToServer.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.JFatCatClient.320.JFatCatClient.sendAFPChainToServer.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.MultipleAlignmentXMLParser.87.TestMultipleAlignmentXMLParser.testRecovery2.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.PDBDomainProvider.143.PDBDomainProvider.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.PdbPairXMLConverter.56.JFatCatClient.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.PDBStatus.584.MMCIFFileReader.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.PositionInQueueXMLConverter.69.JFatCatClient.getPositionInQueue.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.ReadUtils.83.RCSBDescriptionFactoryTest.testUrl.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.RemoteBioUnitDataProvider.152.RemoteBioUnitDataProvider.getNrBiolAssemblies.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.RemoteRawBioUnitDataProvider.143.RemoteRawBioUnitDataProvider.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.RepresentativeXMLConverter.69.GetRepresentatives.getRepresentatives.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.RepresentativeXMLConverter.69.JFatCatClient.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SandboxStyleStructureProvider.184.SandboxStyleStructureProvider.getAllPDBIDs.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SandboxStyleStructureProvider.192.SandboxStyleStructureProvider.getAllPDBIDs.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.ScanSymmetry.76.ScanSymmetry.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.ScanSymmetry.77.ScanSymmetry.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SerializableCache.153.SerializableCache.getCacheFile.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.216.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.225.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.273.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.287.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.299.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.301.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.306.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.315.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.317.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.359.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.381.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.577.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.598.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.SimpleMMcifParser.840.AllChemCompProvider.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.StructureName.231.RemoteDomainProvider.main.truepositive-$bow_app.arff
./run_test.sh 1234 Biojava.StructureTools.1664.FastaAFPChainConverterTest.testCpSymmetric2.falsepositive-$bow_app.arff
./run_test.sh 1234 Biojava.TestLoadStructureFromURL.46.TestLoadStructureFromURL.testLoadStructureFromURL.falsepositive-$bow_app.arff
./run_test.sh 1234 Freecs.GroupManager.175.RequestReader.run.truepositive-$bow_app.arff
./run_test.sh 1234 Freecs.GroupManager.492.RequestReader.run.truepositive-$bow_app.arff
./run_test.sh 1234 Freecs.LogFile.136.LogFile.main.truepositive-$bow_app.arff
./run_test.sh 1234 Freecs.LogFile\$LogFileShrinker.177.LogFile.main.truepositive-$bow_app.arff
./run_test.sh 1234 Freecs.LogFile\$LogFileShrinker.187.LogFile.main.truepositive-$bow_app.arff
./run_test.sh 1234 Freecs.MessageTemplateFinder.48.MessageTemplateFinder.main.truepositive-$bow_app.arff
./run_test.sh 1234 Freecs.MessageTemplateFinder.56.MessageTemplateFinder.main.truepositive-$bow_app.arff
./run_test.sh 1234 Freecs.StaticRequestHandler.78.RequestReader.run.truepositive-$bow_app.arff
./run_test.sh 1234 Freecs.StaticRequestHandler.86.RequestReader.run.truepositive-$bow_app.arff
./run_test.sh 1234 Freecs.StaticRequestHandler.101.RequestReader.run.truepositive-$bow_app.arff
./run_test.sh 1234 Giraph.AllOptions.154.AllOptions.main.truepositive-$bow_app.arff
./run_test.sh 1234 Giraph.AnnotationUtils\$GeneralClassesIterator.197.GiraphRunner.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Giraph.AnnotationUtils\$JarClassesIterator.121.GiraphRunner.run.falsepositive-$bow_app.arff
./run_test.sh 1234 Giraph.FileUtils.58.TestFilters.testVertexFilter.falsepositive-$bow_app.arff
./run_test.sh 1234 Giraph.GeneratePrimitiveClasses.255.GeneratePrimitiveClasses.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Giraph.JMap.98.JMapHistoDumper.startJMapThread.falsepositive-$bow_app.arff
./run_test.sh 1234 Giraph.ZooKeeperManager.434.GraphTaskManager.startZooKeeperManager.falsepositive-$bow_app.arff
./run_test.sh 1234 Giraph.ZooKeeperManager.462.GraphTaskManager.startZooKeeperManager.falsepositive-$bow_app.arff
./run_test.sh 1234 Giraph.ZooKeeperManager.500.GraphTaskManager.startZooKeeperManager.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.BuildBase.390.Build.warConsole.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.CreateCluster.164.CreateCluster.main.truepositive-$bow_app.arff
./run_test.sh 1234 H2.CreateCluster.165.CreateCluster.main.truepositive-$bow_app.arff
./run_test.sh 1234 H2.Db.323.Db.executeQuery.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.Db.338.SamplesTest.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.DbConnection.61.DbConnection.reset.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.Migrate.217.Migrate.main.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.RunScript.283.CreateScriptFile.main.truepositive-$bow_app.arff
./run_test.sh 1234 H2.Script.139.CreateCluster.main.truepositive-$bow_app.arff
./run_test.sh 1234 H2.Shell.456.Shell.main.truepositive-$bow_app.arff
./run_test.sh 1234 H2.SourceCompiler.316.SourceCompiler.getMethod.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.SQLInjection.132.SQLInjection.main.truepositive-$bow_app.arff
./run_test.sh 1234 H2.SQLInjection.190.SQLInjection.main.truepositive-$bow_app.arff
./run_test.sh 1234 H2.SQLInjection.247.SQLInjection.main.truepositive-$bow_app.arff
./run_test.sh 1234 H2.SQLInjection.328.SQLInjection.main.truepositive-$bow_app.arff
./run_test.sh 1234 H2.SQLInjection.350.SQLInjection.main.truepositive-$bow_app.arff
./run_test.sh 1234 H2.TestCompress.153.TestCompress.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestCsv.399.TestCsv.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestCsv.406.TestCsv.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestCsv.487.TestCsv.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestCsv.489.TestCsv.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestCsv.494.TestCsv.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFullText.195.TestFullText.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFullText.200.TestFullText.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFullText.204.TestFullText.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFullText\$1.271.TestFullText.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFullText\$1.291.TestFullText.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFunctionOverload.54.TestFunctionOverload.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFunctionOverload.59.TestFunctionOverload.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFunctionOverload.71.TestFunctionOverload.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFunctionOverload.91.TestFunctionOverload.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFunctionOverload.107.TestFunctionOverload.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFunctions.2200.TestFunctions.addRow.truepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFuzzOptimizations.111.TestFuzzOptimizations.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestFuzzOptimizations.114.TestFuzzOptimizations.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestIndex.239.TestIndex.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestIndexHints.66.TestIndexHints.test.truepositive-$bow_app.arff
./run_test.sh 1234 H2.TestJoin.251.TestJoin.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestJoin.253.TestJoin.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestNativeSQL.253.TestNativeSQL.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestScript.189.TestScript.test.truepositive-$bow_app.arff
./run_test.sh 1234 H2.TestScript.253.TestScript.test.truepositive-$bow_app.arff
./run_test.sh 1234 H2.TestTwoPhaseCommit.98.TestTwoPhaseCommit.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.TestTwoPhaseCommit.100.TestTwoPhaseCommit.test.falsepositive-$bow_app.arff
./run_test.sh 1234 H2.WebApp.1330.WebApp.editResult.truepositive-$bow_app.arff
./run_test.sh 1234 H2.WebApp.1380.WebApp.editResult.truepositive-$bow_app.arff
./run_test.sh 1234 H2.WebApp.1453.WebApp.editResult.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.CodeSwitcher.151.CodeSwitcher.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.CodeSwitcher.153.CodeSwitcher.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.CodeSwitcher.193.CodeSwitcher.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.CodeSwitcher.194.CodeSwitcher.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.CodeSwitcher.299.CodeSwitcher.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.CodeSwitcher.323.CodeSwitcher.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.CodeSwitcher.324.CodeSwitcher.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.CodeSwitcher.475.CodeSwitcher.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.CodeSwitcher.480.CodeSwitcher.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DatabaseManager.349.DatabaseManager.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DatabaseManager.853.DatabaseManager.actionPerformed.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DatabaseManager.1057.DatabaseManager.actionPerformed.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DatabaseManagerCommon.268.DatabaseManager.insertTestData.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DatabaseManagerCommon.272.DatabaseManager.insertTestData.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackup.92.DbBackupMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackup.97.DbBackupMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackup.98.DbBackupMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackup.99.DbBackupMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackup.100.DbBackupMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackup.101.DbBackupMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackup.102.DbBackupMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackup.116.Logger.backup.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackup.121.Logger.backup.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackup.250.Logger.backup.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackupMain.84.DbBackupMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackupMain.104.DbBackupMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackupMain.106.DbBackupMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackupMain.128.DbBackupMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.DbBackupMain.136.DbBackupMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.FileRecordReader.79.FileRecordReader.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.HsqlSocketFactory.125.ClientConnection.openConnection.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.HsqlSocketFactory.140.ClientConnection.openConnection.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.LdapAuthBeanTester.104.LdapAuthBeanTester.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.LdapAuthBeanTester.132.LdapAuthBeanTester.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.Preprocessor.224.PreprocessorAntTask.execute.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.Preprocessor.225.PreprocessorAntTask.execute.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.Preprocessor.322.PreprocessorAntTask.execute.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.Preprocessor.653.Preprocessor.processInclude.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.Preprocessor.656.Preprocessor.processInclude.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.Preprocessor.660.Preprocessor.processInclude.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.Server.1040.Server.setWebRoot.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.ServerAcl.506.ServerAcl.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.Servlet.222.Servlet.doGet.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.Servlet.226.Servlet.doGet.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.SqlFileEmbedder.85.SqlFileEmbedder.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.SqlTool.563.SqlTool.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.TarFileOutputStream.135.TarGeneratorMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.TarGenerator\$TarEntrySupplicant.396.TarGeneratorMain.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.TarGeneratorMain.53.TarGeneratorMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.TarGeneratorMain.59.TarGeneratorMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.TarReader.337.TarReaderMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.TarReader\$TarEntryHeader.583.TarReaderMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.TarReaderMain.55.TarReaderMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.TarReaderMain.85.TarReaderMain.main.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.Testdb.68.Testdb.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.TriggerSample.374.TriggerSample.getConnection.falsepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.TriggerSample.384.TriggerSample.setup.truepositive-$bow_app.arff
./run_test.sh 1234 Hsqldb.WebServerConnection.461.WebServerConnection.run.truepositive-$bow_app.arff
./run_test.sh 1234 Jackrabbit.CooperativeFileLock.150.CooperativeFileLock.acquire.truepositive-$bow_app.arff
./run_test.sh 1234 Jackrabbit.DatabasePersistenceManager.1051.DatabasePersistenceManager.init.falsepositive-$bow_app.arff
./run_test.sh 1234 Jackrabbit.DatabasePersistenceManager.1147.DatabasePersistenceManager.reestablishConnection.falsepositive-$bow_app.arff
./run_test.sh 1234 Jackrabbit.DatabasePersistenceManager.1184.DatabasePersistenceManager.reestablishConnection.falsepositive-$bow_app.arff
./run_test.sh 1234 Jackrabbit.FileBasedNamespaceMappings.149.SlowQueryHandler.doInit.falsepositive-$bow_app.arff
./run_test.sh 1234 Jackrabbit.IndexingQueueStore.145.SearchIndex.doInit.falsepositive-$bow_app.arff
./run_test.sh 1234 Jackrabbit.IndexingQueueStore.155.SearchIndex.doInit.falsepositive-$bow_app.arff
./run_test.sh 1234 Jetty.AbstractDatabaseLoginModule.95.AbstractLoginModule.login.falsepositive-$bow_app.arff
./run_test.sh 1234 Jetty.AbstractDatabaseLoginModule.128.AbstractLoginModule.login.falsepositive-$bow_app.arff
./run_test.sh 1234 Jetty.AbstractHandler.100.AbstractHandler.doError.truepositive-$bow_app.arff
./run_test.sh 1234 Jetty.ContextHandler.1046.ContextHandler.checkContext.truepositive-$bow_app.arff
./run_test.sh 1234 Jetty.ContextHandler.1048.ContextHandler.checkContext.truepositive-$bow_app.arff
./run_test.sh 1234 Jetty.CookieCutter.372.SessionHandler.checkRequestedSessionId.truepositive-$bow_app.arff
./run_test.sh 1234 Jetty.CookieCutter.372.SessionHandler.doScope.truepositive-$bow_app.arff
./run_test.sh 1234 Jetty.GzipHandler.487.GzipHandler.handle.truepositive-$bow_app.arff
./run_test.sh 1234 Jetty.MovedContextHandler\$Redirector.124.MovedContextHandler\$Redirector.handle.truepositive-$bow_app.arff
./run_test.sh 1234 Jetty.ResourceService.263.ResourceService.doGet.truepositive-$bow_app.arff
./run_test.sh 1234 Jetty.ResourceService.302.ResourceService.doGet.falsepositive-$bow_app.arff
./run_test.sh 1234 Jetty.ResourceService.390.ResourceService.sendWelcome.truepositive-$bow_app.arff
./run_test.sh 1234 Jetty.ResourceService.418.ResourceService.sendWelcome.truepositive-$bow_app.arff
./run_test.sh 1234 Jetty.ResourceService.548.ResourceService.passConditionalHeaders.truepositive-$bow_app.arff
./run_test.sh 1234 Jetty.ResourceService.606.ResourceService.passConditionalHeaders.falsepositive-$bow_app.arff
./run_test.sh 1234 Jetty.SecuredRedirectHandler.66.SecuredRedirectHandler.handle.truepositive-$bow_app.arff
./run_test.sh 1234 JodaTime.ZoneInfoCompiler.94.ZoneInfoCompiler.main.truepositive-$bow_app.arff
./run_test.sh 1234 JodaTime.ZoneInfoCompiler.96.ZoneInfoCompiler.main.truepositive-$bow_app.arff
./run_test.sh 1234 JodaTime.ZoneInfoCompiler.118.ZoneInfoCompiler.main.truepositive-$bow_app.arff
./run_test.sh 1234 JodaTime.ZoneInfoCompiler.471.ZoneInfoCompiler.compile.falsepositive-$bow_app.arff
./run_test.sh 1234 JodaTime.ZoneInfoProvider.198.ZoneInfoProvider.\<init\>.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.ChoicePoint.131.ChoiceSelector.\<init\>.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.ClassFile.116.ClassFilePrinter.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.Config.414.JPF.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.Config.531.JPF.main.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.Config.560.JPF.main.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.Config.568.JPF.main.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.Config.726.JPF.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.Config.728.JPF.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.Config.786.JPF.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.Config.889.JPF.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.Config.2103.ClassInfo.makeModelClassPath.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.Config.2115.Config.getPath.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.CoverageAnalyzer.608.CoverageAnalyzer.\<init\>.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.DebugJenkinsStateSet.66.DebugJenkinsStateSet.\<init\>.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.ESParser.76.ESParser.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.FileUtils.83.JPF.main.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.FileUtils.159.JPF.main.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.FileUtils.500.FileUtils.copyFile.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.JPF_gov_nasa_jpf_CachedROHttpConnection.117.JPF_gov_nasa_jpf_CachedROHttpConnection.getContents__Ljava_lang_String_2___3B.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.JPF_java_io_File.42.JPF_java_io_File.canRead____Z.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.JPF_java_io_FileDescriptor.79.JPF_java_io_FileDescriptor.open__Ljava_lang_String_2I__I.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.JPF_java_io_FileDescriptor.104.JPF_java_io_FileDescriptor.open__Ljava_lang_String_2I__I.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.JPF_java_io_FileDescriptor.163.JPF_java_io_FileDescriptor.read____I.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.JPF_java_io_FileDescriptor.169.JPF_java_io_FileDescriptor.read____I.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.JPF_java_lang_System.118.JPF_java_lang_System.getKeyValuePairs_____3Ljava_lang_String_2.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.JPF.512.JPF.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.JPF.689.JPF.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.JPF.690.JPF.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.JPFSiteUtils.55.JPF.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.LogHandler.170.LogHandler.\<init\>.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.PathnameExpander.149.PathnameExpander.expandPath.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.PathnameExpander.152.PathnameExpander.expandPath.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.PathnameExpander.166.PathnameExpander.expandPath.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.PathnameExpander.176.PathnameExpander.expandPath.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.PathOutputMonitor.226.PathOutputMonitor.\<init\>.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.RunJPF.218.JPF.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.RunJPF.220.JPF.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.RunTest.288.RunTest.main.truepositive-$bow_app.arff
./run_test.sh 1234 JPF.Source.160.VM.initSubsystems.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.Source.171.VM.initSubsystems.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.Source.203.Source.findSrcRoot.falsepositive-$bow_app.arff
./run_test.sh 1234 JPF.Source.216.Source.findSrcRoot.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.DefaultVFS.125.DefaultVFS.list.truepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.DefaultVFS.265.DefaultVFS.list.truepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.DefaultVFS.270.DefaultVFS.list.truepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.ExternalResources.75.ExternalResourcesTest.testGetConfiguredTemplate.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.PooledDataSource.527.PooledDataSource.pingConnection.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.PreparedStatementHandler.80.SimpleExecutor.prepareStatement.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.PreparedStatementHandler.82.SimpleExecutor.prepareStatement.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.PreparedStatementHandler.85.SimpleExecutor.prepareStatement.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.PreparedStatementHandler.87.SimpleExecutor.prepareStatement.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.ScriptRunner.235.AbstractLazyTest.before.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.ScriptRunner.246.AbstractLazyTest.before.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.SimpleStatementHandler.67.BaseExecutorTest.shouldDeleteAuthor.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.SqlRunner.80.SqlRunnerTest.shouldUpdateCategory.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.SqlRunner.105.SqlRunnerTest.shouldInsert.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.SqlRunner.107.SqlRunnerTest.shouldInsert.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.SqlRunner.149.SqlRunnerTest.shouldUpdateCategory.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.SqlRunner.184.SqlRunnerTest.shouldDemonstrateDDLThroughRunMethod.falsepositive-$bow_app.arff
./run_test.sh 1234 Mybatis.XPathParser.257.XPathParserTest.shouldTestXPathParserMethods.falsepositive-$bow_app.arff
./run_test.sh 1234 Okhttp3.CacheTest.2453.CacheTest.testGoldenCacheResponse.falsepositive-$bow_app.arff
./run_test.sh 1234 Okhttp3.Http2Server.187.Http2Server.main.truepositive-$bow_app.arff
./run_test.sh 1234 Okhttp3.Main\$1.254.Main.run.truepositive-$bow_app.arff
./run_test.sh 1234 Okhttp3.Main\$2.272.Main.run.truepositive-$bow_app.arff
./run_test.sh 1234 Okhttp3.MockHttp2Peer.181.MockHttp2Peer.openSocket.truepositive-$bow_app.arff
./run_test.sh 1234 Okhttp3.RecordingAuthenticator.35.RecordingAuthenticator.\<init\>.truepositive-$bow_app.arff
./run_test.sh 1234 Okhttp3.SampleServer.45.SampleServer.dispatch.truepositive-$bow_app.arff
./run_test.sh 1234 Okhttp3.SampleServer.122.SampleServer.main.truepositive-$bow_app.arff
./run_test.sh 1234 Okhttp3.SocksProxy.185.SocksProxy.acceptCommand.truepositive-$bow_app.arff
./run_test.sh 1234 Okhttp3.SslClient\$Builder.145.SslClient\$Builder.build.truepositive-$bow_app.arff
./run_test.sh 1234 Okhttp3.UrlConnectionCacheTest.1670.UrlConnectionCacheTest.testGoldenCacheResponse.falsepositive-$bow_app.arff
./run_test.sh 1234 Okhttp3.URLConnectionTest.1945.URLConnectionTest.authenticateWithCharset.truepositive-$bow_app.arff
owasp
./run_test.sh 1234 Susi.AIML2Susi.55.AIML2Susi.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.AIML2Susi.55.SusiMind.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.AIML2Susi.55.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.AIML2Susi.55.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.AIML2Susi.118.AIML2Susi.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.AppsService.66.AbstractAPIHandler.doPost.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.Caretaker.53.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.CreateSkillService.87.CreateSkillService.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.CreateSkillService.92.CreateSkillService.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.CreateSkillService.97.CreateSkillService.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.CreateSkillService.135.CreateSkillService.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.CreateSkillService.136.CreateSkillService.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.CreateSkillService.138.CreateSkillService.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.CreateSkillService.167.CreateSkillService.doPost.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.CreateSkillService.174.CreateSkillService.doPost.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.DAO.355.SusiMind.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.DAO.355.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.DAO.355.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.DeleteSkillService.49.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.DeleteSkillService.51.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.DeleteSkillService.53.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.DeleteSkillService.65.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.DeleteSkillService.68.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.DisableSkillService.70.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.DisableSkillService.72.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.DisableSkillService.74.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.DisableSkillService.76.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.EnableSkillService.69.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.EnableSkillService.71.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.EnableSkillService.73.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.EnableSkillService.75.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.GetAllLanguages.60.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.GetAllLanguages.62.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.GetFileAtCommitID.51.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.GetFileAtCommitID.53.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.GetFileAtCommitID.55.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.GetSkillJsonService.67.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.GetSkillJsonService.69.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.GetSkillJsonService.71.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.GroupListService.46.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.GroupListService\$1.51.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonFile.95.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonFile.95.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonFile.96.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonFile.96.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.134.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.134.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.135.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.135.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.152.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.152.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.153.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.153.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.161.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.161.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.170.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.170.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.178.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.JsonRepository.178.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.103.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.108.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.113.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.125.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.130.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.135.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.140.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.191.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.193.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.235.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.271.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.273.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.314.AbstractAPIHandler.doPost.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.321.AbstractAPIHandler.doPost.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.ModifySkillService.351.AbstractAPIHandler.doPost.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.RateSkillService.63.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiMemory.254.SusiMind.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiMemory.254.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiMemory.254.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiServer.311.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiServer.316.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiServer.335.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiServer.339.SusiServer.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiSkill.423.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiSkill.431.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiSkill.436.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiSkill.444.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiSkill.457.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.SusiSkill.462.SusiSkill.main.falsepositive-$bow_app.arff
./run_test.sh 1234 Susi.UndoDeleteSkillService.63.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.UndoDeleteSkillService.65.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.UndoDeleteSkillService.67.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.UndoDeleteSkillService.76.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 Susi.UndoDeleteSkillService.79.AbstractAPIHandler.doPost.truepositive-$bow_app.arff
./run_test.sh 1234 UPM.DatabaseActions.391.DatabaseActions.openDatabase.truepositive-$bow_app.arff
./run_test.sh 1234 UPM.Preferences.105.DatabaseActions.newDatabase.truepositive-$bow_app.arff
./run_test.sh 1234 UPM.Preferences.138.Preferences.load.falsepositive-$bow_app.arff
./run_test.sh 1234 UPM.Preferences.147.Preferences.load.falsepositive-$bow_app.arff
./run_test.sh 1234 UPM.Preferences.160.DatabaseActions.newDatabase.falsepositive-$bow_app.arff
./run_test.sh 1234 UPM.TestPasswordDatabase.48.TestPasswordDatabase.testOpenNonExistantFile.falsepositive-$bow_app.arff
./run_test.sh 1234 UPM.TestPasswordDatabase.52.TestPasswordDatabase.testOpenNonExistantFile.falsepositive-$bow_app.arff
./run_test.sh 1234 UPM.TestPasswordDatabase.65.TestPasswordDatabase.testOpenExistingDB.falsepositive-$bow_app.arff
./run_test.sh 1234 UPM.TestPasswordDatabase.71.TestPasswordDatabase.testOpenExistingDB.falsepositive-$bow_app.arff
./run_test.sh 1234 UPM.TestPasswordDatabase.80.TestPasswordDatabase.testAddAccount.falsepositive-$bow_app.arff
./run_test.sh 1234 UPM.TestPasswordDatabase.94.TestPasswordDatabase.testAddAccount.falsepositive-$bow_app.arff
./run_test.sh 1234 UPM.TestPasswordDatabase.111.TestPasswordDatabase.testRemoveAccount.falsepositive-$bow_app.arff
./run_test.sh 1234 UPM.TestPasswordDatabase.130.TestPasswordDatabase.testRemoveAccount.falsepositive-$bow_app.arff
./run_test.sh 1234 UPM.TestPasswordDatabase.137.TestPasswordDatabase.testRemoveAccount.falsepositive-$bow_app.arff
./run_test.sh 1234 UPM.TestPasswordDatabase.156.TestPasswordDatabase.deleteFile.falsepositive-$bow_app.arff